services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pedidos_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: 
      context: .
      dockerfile: Dockerfile          
    container_name: pedidos_app    
    ports:
      - 3333:3333
      - 9229:9229 #porta para debug
    volumes:
      - ./src:/usr/src/app/src 

    environment:
      - APP_PORT=3333
      - DB_DATABASE=pedidos_db
      - DB_USER=docker
      - DB_PASS=docker
      - DB_HOST=postgres-db
      - DB_PORT=5432     
      - RABBITMQ_URL=amqp://localhost
    links:
      - postgres-db

    depends_on:
      - postgres-db  

volumes:
  pgdata:
    driver: local
    